name: Deployment

on:
  workflow_dispatch:
    inputs:
      Environ:
        description: 'Environment'
        required: true
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  Dev:
    if: ${{ github.event.inputs.Environ == 'dev' }}
    runs-on: ubuntu-latest
    environment: dev
    steps:
    
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Environ }}"
      - name: multiline scripe
        run: |
          git ls-tree --name-only HEAD | xargs -I {} sh -c 'touch -d "$(git log -1 --format="%ci" "{}")" "{}"'
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
        
    #  - name: time script
    #    run: |
    #      bash time.sh
    #    shell: bash
        
      - name: Run script
        run: |
          chmod +x time.sh
          ./time.sh        
        
        
  Stage:
    if: ${{ github.event.inputs.Environ == 'stage' }}
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Environ }}"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python        


  Prod:
    if: ${{ github.event.inputs.Environ == 'prod' }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Environ }}"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python        
