name: Shell Commands

on:
  workflow_dispatch:
    inputs:
      Environ:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  run-shell-commands:
    if: ${{ github.event.inputs.Enviro == 'stage' }}  
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
