name: Deployment

on:
  workflow_dispatch:
    inputs:
      Environ:
        description: 'Environment'
        required: true
        default: 'dev'
        type: choice
        options:
        - dev
        - stage
        - prod

jobs:
  Dev:
    if: ${{ github.event.inputs.Enviro == 'dev' }}  
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Enviro }}"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
        
  Stage:
    if: ${{ github.event.inputs.Enviro == 'stage' }}  
    runs-on: ubuntu-latest
    environment: stage
    steps:
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Enviro }}"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python        


  Prod:
    if: ${{ github.event.inputs.Enviro == 'prod' }}  
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: echo a string
        run: echo "Hello World, Deploying in ${{ github.event.inputs.Enviro }}"
      - name: multiline scripe
        run: |
          node -v
          npm -v
          uname -a
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python        
